version: '1.1'
name: Status Check
env:
  host: http://localhost:4000
tests:
  example:
    steps:
      - name: Status
        http:
          url: ${{env.host}}
          method: GET
          check:
            status: 200
            jsonpath:
              $.status:
                - eq: 'ok'
                - isString: true
      - name: GraphQL
        http:
          url: ${{env.host}}/graphql
          graphql:
            query: |
              query {
                allUsers{
                  name,
                  email,
                  id,
                  posts{
                  id
                }
                }
              }
          check:
            status: 200
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    allUsers:
                      type: array
                  required:
                    - allUsers
              required:
                - data
